In [1]:
import numpy as np
arr = np.random.randint(2, size = (10,))
indx = np.where(arr==2)[0]
print(len(indx))

0


In [2]:
x = np.arange(9).reshape((3,3))
for x in np.diag(x):
    print(x, end=",")

0,4,8,

In [3]:
import numpy as np
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
for x in data[::-1]:
    print(x, end=" ")

9 8 7 6 5 4 3 2 1 

In [4]:
import numpy as np
a = np.array([[3, 2], [3, -1], [3, 5]])
for x in a.mean(axis=1):
    print(x, end=',')

2.5,1.0,4.0,

In [5]:
import numpy as np

a = np.array([[1, 2, 3],[4, 5, 6]])
b = a.reshape(2,-1)
print(b.shape)

(2, 3)


In [6]:
from scipy.optimize import minimize

# Define the objective function
def objective_function(x):
    return (x[0] - 2) ** 2 + (x[1] - 3) ** 2

initial_guess = [0, 0]
result = minimize(objective_function, initial_guess)

for indx, val in enumerate(result.x):
    print(f'x[{indx}] = {round(val)}', end=', ')

x[0] = 2, x[1] = 3, 

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a,b))
print(c.shape)

(2, 3)


In [8]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped = array.reshape((2, 4, 2))

# printing reshaped array
print("Reshaped 3-D Array : ")
print(reshaped)


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 3-D Array : 
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [9]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([[1, 2, 3],
				[4, 5, 6],
				[7, 8, 9]])

# printing array
print(" 2-D Array : ")
print(array)


# reshaping numpy array
# converting it to 1-D from 2-D array
# reshaping it into 1, 5
reshaped = array.reshape((3, 3))

# or we can use 

# printing reshaped array
print("Reshaped 1-D Array : ")
print(reshaped)


 2-D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped 1-D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# import the important module in python 
import numpy as np 
		
# make matrix with numpy 
gfg = np.matrix('[64, 1; 12, 3]') 
		
# applying matrix.resize() method 
geeks = gfg.resize((1, 4)) 
	
print(geeks) 


None


In [11]:
# import the important module in python 
import numpy as np 
		
# make matrix with numpy 
gfg = np.matrix('[64, 1; 12, 3]') 
		
# applying matrix.resize() method 
geeks = gfg.resize((1, 4)) 
	
print(geeks) 


None
