In [21]:
import numpy as np
a = np.array([[[1,2,3],[2,6,7]],[[2,3,4],[4,6,7]]])
b = np.array([1,2,3])
print(a)
print(a.ndim)
print(b.ndim)
print(type(a))

[[[1 2 3]
  [2 6 7]]

 [[2 3 4]
  [4 6 7]]]
3
1
<class 'numpy.ndarray'>


In [5]:
import numpy as np
a = np.array([2,3])
print(a)

[2 3]


In [1]:
import numpy as np
a = np.asarray([10,20,30])
print(a)

[10 20 30]


In [1]:
import numpy as np

x = np.array([1,2.4], dtype='int8')


In [5]:
res = np.asarray(a,dtype="float",order="C")
print(res)

[10. 20. 30.]


In [4]:
import numpy as np
np.arange(0,10,3,dtype="int")

array([0, 3, 6, 9])

In [23]:
a = np.zeros((2,3))
print(a)
d = np.full((3,3), 4, dtype = 'complex')
print(d)
e = np.random.random((2,5))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j]]
[[0.3783867  0.40036195 0.2753181  0.66565596 0.0177586 ]
 [0.02992611 0.43961429 0.0167905  0.47244297 0.25134465]]


In [26]:
#sequence
a = np.arange(0, 30, 5)
print(a)



[ 0  5 10 15 20 25]


In [27]:
b = np.linspace(1,20,4)
print(b)

[ 1.          7.33333333 13.66666667 20.        ]


In [32]:
#reshape array
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,6,7]])
newarr = arr.reshape(2,2,3)
print("oroginal:",arr)
print("reshape:",newarr)

oroginal: [[1 2 3 4]
 [5 6 7 8]
 [9 0 6 7]]
reshape: [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 6 7]]]


In [33]:
#flatten array
arr = np.array([[1,2,3],[4,5,6]])
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [34]:
# Python program to demonstrate sorting in numpy 
import numpy as np 

a = np.array([[1, 4, 2], 
				[3, 4, 6], 
			[0, -1, 5]]) 

# sorted array 
print ("Array elements in sorted order:\n", 
					np.sort(a, axis = None)) 

# sort array row-wise 
print ("Row-wise sorted array:\n", 
				np.sort(a, axis = 1)) 

# specify sort algorithm 
print ("Column wise sort by applying merge-sort:\n", 
			np.sort(a, axis = 0, kind = 'mergesort')) 

# Example to show sorting of structured array 
# set alias names for dtypes 
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 

# Values to be put in array 
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
		('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
			
# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n", 
			np.sort(arr, order = 'name')) 
			
print ("Array sorted by graduation year and then cgpa:\n", 
				np.sort(arr, order = ['grad_year', 'cgpa'])) 


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


^C
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numba as nb

# Define a function that calculates the sum of squares
def sum_of_squares(n):
    result = 0
    for i in range(n):
        result += i * i
    return result

# Define the same function, but decorate it with Numba's @jit decorator for acceleration
@nb.jit
def numba_sum_of_squares(n):
    result = 0
    for i in range(n):
        result += i * i
    return result

# Test the original function
print("Original function:")
%timeit sum_of_squares(1000000)

# Test the Numba-accelerated function
print("\nNumba-accelerated function:")
%timeit numba_sum_of_squares(1000000)


Original function:
100 ms ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Numba-accelerated function:
The slowest run took 27.00 times longer than the fastest. This could mean that an intermediate result is being cached.
1.99 µs ± 3.6 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [2]:
from numba import jit
import numpy as np

x = np.arange(100).reshape(10, 10)

@jit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0.0
    for i in range(a.shape[0]):   # Numba likes loops
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

print(go_fast(x))

[[  9.  10.  11.  12.  13.  14.  15.  16.  17.  18.]
 [ 19.  20.  21.  22.  23.  24.  25.  26.  27.  28.]
 [ 29.  30.  31.  32.  33.  34.  35.  36.  37.  38.]
 [ 39.  40.  41.  42.  43.  44.  45.  46.  47.  48.]
 [ 49.  50.  51.  52.  53.  54.  55.  56.  57.  58.]
 [ 59.  60.  61.  62.  63.  64.  65.  66.  67.  68.]
 [ 69.  70.  71.  72.  73.  74.  75.  76.  77.  78.]
 [ 79.  80.  81.  82.  83.  84.  85.  86.  87.  88.]
 [ 89.  90.  91.  92.  93.  94.  95.  96.  97.  98.]
 [ 99. 100. 101. 102. 103. 104. 105. 106. 107. 108.]]


In [10]:
arr=np.arange(0,10,3,dtype="float")
print(arr)

[0. 3. 6. 9.]


In [14]:
np.linspace(0,10,5,endpoint="false",retstep="true")

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

In [22]:
arr=np.logspace(0,20,num=6,endpoint=False,base=2)
print(arr)

[1.00000000e+00 1.00793684e+01 1.01593667e+02 1.02400000e+03
 1.03212732e+04 1.04031915e+05]


In [9]:
import numpy as np
array= np.array([[10,20,30],[20,30,40]])
print(array)
np.reshape(array,(3,2))

[[10 20 30]
 [20 30 40]]


array([[10, 20],
       [30, 20],
       [30, 40]])

In [24]:
np.eye((6))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [43]:
a = np.array([[[10,20,30,40],[20,30,40,50]],
[[20,30,40,80],[30,40,50,60]]])
print("a[0,1,2]=",a[0,1,2])

a[0,1,2]= 40


In [33]:
import numpy as np
a=np.array([[40,10,30,],[1,5,15]])
np.sort(a,axis=1)

array([[10, 30, 40],
       [ 1,  5, 15]])

In [4]:
import numpy as np
a=np.array(['a','20','9'])
print(a)
print(a.dtype)

['a' '20' '9']
<U2


In [22]:
import numpy as np
a=np.array(['8','20','9'])
print(a)
print(a.dtype)
c=a.copy()
c[2]=30
print(c.base)

['8' '20' '9']
<U2
None


In [25]:
import numpy as np
a=np.arange(6).reshape(3,2)
a
b=np.arange(7,13).reshape(3,2)
b
#np.concatenate((a,b))
#np.concatenate((a,b),axis=1)
#np.stack((a,b))
np.hstack((a,b))
#p.dstack((a,b))

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [4]:
import numpy as np
a=np.array([20,30,50,70,10])
np.sort(a)



array([10, 20, 30, 50, 70])

In [7]:
import numpy as np
b=np.array([[20,30,50], [70,10,100]])
np.sort(b,axis=0)


array([[ 20,  10,  50],
       [ 70,  30, 100]])

In [17]:
import numpy as np
d=np.dtype([('name','S10'),('perc',float)])
stud=np.array([("abc",90.3,("def",56.7)),("ghi",56.9)])
stud

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [16]:
print(2***2)

SyntaxError: invalid syntax (3118448607.py, line 1)

In [27]:
import numpy as np
a=np.array([[1,2,8],[4,5,6]])
b=np.array([[2,3,4],[2,3,4]])
print(a,b)
np.shape(a)
np.shape(b)
np.add(a,b)
c=np.array([10,20,3])
np.shape(c)
np.add(b,c)

[[1 2 8]
 [4 5 6]] [[2 3 4]
 [2 3 4]]


array([[12, 23,  7],
       [12, 23,  7]])

In [30]:
e=np.array([10])
print(e)
np.shape(e)
np.subtract(a,e)

[10]


array([[-9, -8, -2],
       [-6, -5, -4]])

In [12]:
import numpy as np
#create ary obj
arr =np.array ( [[1.0, 2.2, 3.2],
                [5.8, 6.8, 2.7]] )
print("array is type:",type(arr))
print("no.of dem:",arr.ndim)
print("shape of array:",arr.shape)
print("size of array:",arr.size)
print("array stores elements in type:",arr.dtype)

array is type: <class 'numpy.ndarray'>
no.of dem: 2
shape of array: (2, 3)
size of array: 6
array stores elements in type: float64


In [1]:
import numpy as np
arr = np.random.randint(2, size = (10,))
indx = np.where(arr==2)[0]
print(len(indx))

0


In [2]:
import numpy as np
a = np.array([[3, 2], [3, -1], [3, 5]])
for x in a.mean(axis=0):
    print(x, end=',')

3.0,2.0,

In [6]:
# import the important module in python 
import numpy as np 
		
# make matrix with numpy 
gfg = np.matrix('[64, 1; 12, 9; 5, 3]') 
		
# applying matrix.resize() method 
geeks = gfg.resize((2, 3)) 
	
print(geeks) 


None


In [8]:
import numpy as np
arr = np.arange(16.0).reshape(4,4)
nar = np.hsplit(arr,2)
print(nar)

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


In [18]:
import numpy as np 
# Create a sequence of integers from 10 to 1 with a step of -2 
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a) 
# Indexes are specified inside the np.array method. 
newarr = a[np.array([1, 4, 3 ])] 
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [8 2 4]


In [2]:
import numpy as np
arr = [1, True, 2, 2, 3]
x, y = np.unique(arr, return_counts = True)

In [8]:
import numpy as np
arr = np.array(2,6)
print(arr)

TypeError: Cannot interpret '6' as a data type

In [15]:
import numpy as np 
# Arrange elements from 0 to 19 
a = np.arange(20) 
print("\n Array is:\n ",a) 
print("\n a[15]=",a[15]) 
# a[start:stop:step] 
print("\n a[-8:17:1] = ",a[-8:15:2]) 
print("\n a[10:] = ",a[10:])



 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[15]= 15

 a[-8:17:1] =  [12 14]

 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


In [1]:
import numpy as np

x = np.array([1,2.4], dtype='int8')




In [ ]:
from numba import jit
import numpy as np

x = np.arange(100).reshape(10, 10)

@jit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0.0
    for i in range(a.shape[0]):   # Numba likes loops
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

print(go_fast(x))